/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type State = "processing";
export type Text = string;
export type Type = "ack";
export type Event = "start" | "end" | "stop";
export type Format = "pcm16" | null;
export type SampleRate = number | null;
export type Type1 = "audio_out";
export type Available = boolean;
export type ListingId = string;
export type Email = string;
export type ListingId1 = string;
export type SessionId = string;
export type SlotStartIst = string;
export type CalendarSync = "complete" | "reconciling";
export type Code = string;
export type ListingId2 = string;
export type PdfStatus = "pending" | "sent" | "failed" | "render_failed" | "rate_limited" | "not_applicable";
export type EndIst = string;
export type Spoken = string;
export type StartIst = string;
export type State1 = "offered" | "confirming" | "booked" | "cancelled" | "withdrawn";
export type Spoken1 = string;
export type Code1 = string;
export type ContractVersion = string;
export type Type2 = "hello";
export type ContractVersion1 = string;
export type SessionId1 = string;
export type Type3 = "hello";
export type Outcome = Answered | Empty | Degraded | Failed | NeedsInput;
export type Kind = "answered";
export type Spoken2 = string;
export type ConstraintsReadback = string[];
export type CitationRefs = string[];
export type Text1 = string;
export type Claims = ClaimVM[];
export type Gaps = string[];
export type ListingId3 = string;
export type Opener = string;
export type AsOf = string | null;
export type Label = string;
export type Method = string | null;
export type Ref = string;
export type Timing = string | null;
export type Title = string | null;
export type Url = string | null;
export type Sources = CitationVM[];
export type Notices = string[];
export type OfferedSlots = SlotVM[];
export type Amenities = string[];
export type AvailableFrom = string;
export type BhkType = string;
export type Deposit = string;
export type Floor = string;
export type Furnishing = string;
export type ListingId4 = string;
export type Locality = string;
export type Maintenance = string;
export type Parking = string;
export type Rank = number;
export type Rent = string;
export type SocietyName = string;
export type SquareFootage = string;
export type Badge = string;
export type FullLabel = string;
export type Spoken3 = string;
export type ValueText = string;
export type What = string;
export type Cards = CardVM[];
export type Count = number;
export type Locality1 = string;
export type Groups = LocalityGroupVM[];
export type Order = string[];
export type Field = string;
export type ListingIds = string[];
export type Spoken4 = string;
export type UnknownOn = UnknownGroupVM[];
export type Claims1 = ClaimVM[];
export type Gaps1 = string[];
export type Limited = boolean;
export type ListingId5 = string;
export type Kind1 = "empty";
export type Spoken5 = string;
export type Suggestions = string[];
export type Binding = boolean;
export type Field1 = string;
export type Value = string;
export type Unmet = UnmetConstraint[];
export type Kind2 = "degraded";
export type Missing = string[];
export type Spoken6 = string;
export type Why = string;
export type Capability = "speech_in" | "understanding" | "explanation" | "speech_out" | "calendar" | "mail";
export type Kind3 = "failed";
export type RetryWorthIt = boolean;
export type Spoken7 = string;
export type TellRenter = string;
export type Field2 = string;
export type Kind4 = "needs_input";
export type Options = string[];
export type Question = string;
export type Spoken8 = string;
export type Type4 = "outcome";
export type Code2 = string;
export type PdfStatus1 = "pending" | "sent" | "failed" | "render_failed" | "rate_limited" | "not_applicable";
export type Spoken9 = string;
export type Code3 = string;
export type SlotStartIst1 = string;
export type ListingId6 = string;
export type Slots = SlotVM[];
export type Spoken10 = string;
export type Type5 = "stop";
export type Text2 = string;
export type Type6 = "text";
export type Final = boolean;
export type Text3 = string;
export type Type7 = "transcript";

/**
 * A root model whose fields pull every message and body into one $defs table.
 */
export interface ScoutContractV1 {
  ack: AckMsg;
  audio_out: AudioOutMsg;
  availability_toggle: AvailabilityToggle;
  booking_request: BookingRequest;
  booking_response: BookingResponse;
  cancel_request: CancelRequest;
  hello_in: HelloIn;
  hello_out: HelloOut;
  outcome: OutcomeMsg;
  pdf_status_response: PdfStatusResponse;
  reschedule_request: RescheduleRequest;
  slots_request: SlotsRequest;
  slots_response: SlotsResponse;
  stop_in: StopIn;
  text_in: TextIn;
  transcript: TranscriptMsg;
}
export interface AckMsg {
  state?: State;
  text: Text;
  type?: Type;
}
export interface AudioOutMsg {
  event: Event;
  format?: Format;
  sample_rate?: SampleRate;
  type?: Type1;
}
export interface AvailabilityToggle {
  available: Available;
  listing_id: ListingId;
}
export interface BookingRequest {
  email: Email;
  listing_id: ListingId1;
  session_id: SessionId;
  slot_start_ist: SlotStartIst;
}
export interface BookingResponse {
  booking: BookingVM;
  spoken: Spoken1;
}
export interface BookingVM {
  calendar_sync: CalendarSync;
  code: Code;
  listing_id: ListingId2;
  pdf_status: PdfStatus;
  slot: SlotVM;
  state: State1;
}
export interface SlotVM {
  end_ist: EndIst;
  spoken: Spoken;
  start_ist: StartIst;
}
export interface CancelRequest {
  code: Code1;
}
export interface HelloIn {
  contract_version: ContractVersion;
  type?: Type2;
}
export interface HelloOut {
  contract_version: ContractVersion1;
  session_id: SessionId1;
  type?: Type3;
}
export interface OutcomeMsg {
  outcome: Outcome;
  type?: Type4;
}
export interface Answered {
  kind?: Kind;
  spoken: Spoken2;
  view_model: AnsweredViewModel;
}
export interface AnsweredViewModel {
  booking?: BookingVM | null;
  constraints_readback?: ConstraintsReadback;
  explanation?: ExplanationVM | null;
  notices?: Notices;
  offered_slots?: OfferedSlots;
  shortlist?: ShortlistVM | null;
  snapshot?: SnapshotVM | null;
}
export interface ExplanationVM {
  claims: Claims;
  gaps: Gaps;
  listing_id: ListingId3;
  opener: Opener;
  sources: Sources;
}
export interface ClaimVM {
  citation_refs: CitationRefs;
  text: Text1;
}
export interface CitationVM {
  as_of?: AsOf;
  label: Label;
  method?: Method;
  ref: Ref;
  timing?: Timing;
  title?: Title;
  url?: Url;
}
export interface ShortlistVM {
  groups: Groups;
  order: Order;
  unknown_on?: UnknownOn;
}
export interface LocalityGroupVM {
  cards: Cards;
  count: Count;
  locality: Locality1;
}
export interface CardVM {
  amenities: Amenities;
  available_from: AvailableFrom;
  bhk_type: BhkType;
  deposit: Deposit;
  floor: Floor;
  furnishing: Furnishing;
  listing_id: ListingId4;
  locality: Locality;
  maintenance: Maintenance;
  parking: Parking;
  rank: Rank;
  rent: Rent;
  society_name: SocietyName;
  square_footage: SquareFootage;
  transit: CommuteRowVM;
  your_commute?: CommuteRowVM | null;
}
export interface CommuteRowVM {
  badge: Badge;
  full_label: FullLabel;
  spoken: Spoken3;
  value_text: ValueText;
  what: What;
}
export interface UnknownGroupVM {
  field: Field;
  listing_ids: ListingIds;
  spoken: Spoken4;
}
export interface SnapshotVM {
  claims: Claims1;
  gaps: Gaps1;
  limited: Limited;
  listing_id: ListingId5;
}
export interface Empty {
  kind?: Kind1;
  spoken: Spoken5;
  suggestions: Suggestions;
  unmet: Unmet;
}
export interface UnmetConstraint {
  binding: Binding;
  field: Field1;
  value: Value;
}
export interface Degraded {
  kind?: Kind2;
  missing: Missing;
  spoken: Spoken6;
  view_model: AnsweredViewModel;
  why: Why;
}
export interface Failed {
  capability: Capability;
  kind?: Kind3;
  retry_worth_it: RetryWorthIt;
  spoken: Spoken7;
  tell_renter: TellRenter;
}
export interface NeedsInput {
  field: Field2;
  kind?: Kind4;
  options?: Options;
  question: Question;
  spoken: Spoken8;
}
export interface PdfStatusResponse {
  code: Code2;
  pdf_status: PdfStatus1;
  spoken: Spoken9;
}
export interface RescheduleRequest {
  code: Code3;
  slot_start_ist: SlotStartIst1;
}
export interface SlotsRequest {
  listing_id: ListingId6;
}
export interface SlotsResponse {
  slots: Slots;
  spoken: Spoken10;
}
/**
 * The renter tapped Stop while she was speaking: stop the rest of the reply (D2,
 * 2026-09-17). The mic stays muted during playback, so this is the way to interrupt.
 */
export interface StopIn {
  type?: Type5;
}
export interface TextIn {
  text: Text2;
  type?: Type6;
}
export interface TranscriptMsg {
  final: Final;
  text: Text3;
  type?: Type7;
}
